// <auto-generated />
using System;
using Imaginarium.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Imaginarium.Persistance.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210926171953_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Association", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("NomineeId")
                        .HasColumnType("int");

                    b.Property<string>("Phrase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoundId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NomineeId")
                        .IsUnique()
                        .HasFilter("[NomineeId] IS NOT NULL");

                    b.HasIndex("RoundId")
                        .IsUnique();

                    b.ToTable("Association");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CollectionId")
                        .HasColumnType("int");

                    b.Property<int?>("DeckId")
                        .HasColumnType("int");

                    b.Property<int?>("HandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("DeckId");

                    b.HasIndex("HandId");

                    b.HasIndex("Name", "CollectionId")
                        .IsUnique();

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Choice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<int?>("GamerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("CardId", "ElectionId")
                        .IsUnique();

                    b.HasIndex("GamerId", "ElectionId")
                        .IsUnique()
                        .HasFilter("[GamerId] IS NOT NULL");

                    b.ToTable("Choice");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Choice");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Name", "UserId")
                        .IsUnique();

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("Deck");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Election", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RoundId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoundId")
                        .IsUnique();

                    b.ToTable("Election");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LobbyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LobbyId")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Gamer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPresenter")
                        .HasColumnType("bit");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Gamers");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Hand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GamerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GamerId")
                        .IsUnique();

                    b.ToTable("Hand");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Lobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CollectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LobbyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LobbyId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ChoiceId")
                        .HasColumnType("int");

                    b.Property<int?>("GamerId")
                        .HasColumnType("int");

                    b.Property<int>("VotingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChoiceId");

                    b.HasIndex("VotingId");

                    b.HasIndex("GamerId", "VotingId")
                        .IsUnique()
                        .HasFilter("[GamerId] IS NOT NULL");

                    b.ToTable("Vote");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Voting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RoundId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoundId")
                        .IsUnique();

                    b.ToTable("Voting");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Nominee", b =>
                {
                    b.HasBaseType("Imaginarium.Persistance.Entities.Choice");

                    b.HasDiscriminator().HasValue("Nominee");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Association", b =>
                {
                    b.HasOne("Imaginarium.Persistance.Entities.Nominee", "Nominee")
                        .WithOne("Association")
                        .HasForeignKey("Imaginarium.Persistance.Entities.Association", "NomineeId");

                    b.HasOne("Imaginarium.Persistance.Entities.Round", "Round")
                        .WithOne("Association")
                        .HasForeignKey("Imaginarium.Persistance.Entities.Association", "RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nominee");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Card", b =>
                {
                    b.HasOne("Imaginarium.Persistance.Entities.Collection", "Collection")
                        .WithMany("Cards")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Imaginarium.Persistance.Entities.Deck", null)
                        .WithMany("Cards")
                        .HasForeignKey("DeckId");

                    b.HasOne("Imaginarium.Persistance.Entities.Hand", null)
                        .WithMany("Cards")
                        .HasForeignKey("HandId");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Choice", b =>
                {
                    b.HasOne("Imaginarium.Persistance.Entities.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Imaginarium.Persistance.Entities.Election", "Election")
                        .WithMany("Choices")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Imaginarium.Persistance.Entities.Gamer", "Gamer")
                        .WithMany()
                        .HasForeignKey("GamerId");

                    b.Navigation("Card");

                    b.Navigation("Election");

                    b.Navigation("Gamer");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Collection", b =>
                {
                    b.HasOne("Imaginarium.Persistance.Entities.User", "User")
                        .WithMany("Collections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Deck", b =>
                {
                    b.HasOne("Imaginarium.Persistance.Entities.Game", "Game")
                        .WithOne("Deck")
                        .HasForeignKey("Imaginarium.Persistance.Entities.Deck", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Election", b =>
                {
                    b.HasOne("Imaginarium.Persistance.Entities.Round", "Round")
                        .WithOne("Election")
                        .HasForeignKey("Imaginarium.Persistance.Entities.Election", "RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Game", b =>
                {
                    b.HasOne("Imaginarium.Persistance.Entities.Lobby", "Lobby")
                        .WithOne("Game")
                        .HasForeignKey("Imaginarium.Persistance.Entities.Game", "LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lobby");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Gamer", b =>
                {
                    b.HasOne("Imaginarium.Persistance.Entities.Game", "Game")
                        .WithMany("Gamers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Imaginarium.Persistance.Entities.User", "User")
                        .WithOne("Gamer")
                        .HasForeignKey("Imaginarium.Persistance.Entities.Gamer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Hand", b =>
                {
                    b.HasOne("Imaginarium.Persistance.Entities.Gamer", "Gamer")
                        .WithOne("Hand")
                        .HasForeignKey("Imaginarium.Persistance.Entities.Hand", "GamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gamer");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Lobby", b =>
                {
                    b.HasOne("Imaginarium.Persistance.Entities.Collection", "Collection")
                        .WithMany("Lobbies")
                        .HasForeignKey("CollectionId");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Round", b =>
                {
                    b.HasOne("Imaginarium.Persistance.Entities.Game", "Game")
                        .WithMany("Rounds")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.User", b =>
                {
                    b.HasOne("Imaginarium.Persistance.Entities.Lobby", "Lobby")
                        .WithMany("Users")
                        .HasForeignKey("LobbyId");

                    b.Navigation("Lobby");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Vote", b =>
                {
                    b.HasOne("Imaginarium.Persistance.Entities.Choice", "Choice")
                        .WithMany()
                        .HasForeignKey("ChoiceId");

                    b.HasOne("Imaginarium.Persistance.Entities.Gamer", "Gamer")
                        .WithMany()
                        .HasForeignKey("GamerId");

                    b.HasOne("Imaginarium.Persistance.Entities.Voting", "Voting")
                        .WithMany("Votes")
                        .HasForeignKey("VotingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Choice");

                    b.Navigation("Gamer");

                    b.Navigation("Voting");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Voting", b =>
                {
                    b.HasOne("Imaginarium.Persistance.Entities.Round", "Round")
                        .WithOne("Voting")
                        .HasForeignKey("Imaginarium.Persistance.Entities.Voting", "RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Collection", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Lobbies");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Deck", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Election", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Game", b =>
                {
                    b.Navigation("Deck");

                    b.Navigation("Gamers");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Gamer", b =>
                {
                    b.Navigation("Hand");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Hand", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Lobby", b =>
                {
                    b.Navigation("Game");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Round", b =>
                {
                    b.Navigation("Association");

                    b.Navigation("Election");

                    b.Navigation("Voting");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.User", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("Gamer");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Voting", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Imaginarium.Persistance.Entities.Nominee", b =>
                {
                    b.Navigation("Association");
                });
#pragma warning restore 612, 618
        }
    }
}
